# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _neutube
else:
    import _neutube

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _neutube.delete_SwigPyIterator

    def value(self):
        return _neutube.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _neutube.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _neutube.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _neutube.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _neutube.SwigPyIterator_equal(self, x)

    def copy(self):
        return _neutube.SwigPyIterator_copy(self)

    def next(self):
        return _neutube.SwigPyIterator_next(self)

    def __next__(self):
        return _neutube.SwigPyIterator___next__(self)

    def previous(self):
        return _neutube.SwigPyIterator_previous(self)

    def advance(self, n):
        return _neutube.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _neutube.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _neutube.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _neutube.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _neutube.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _neutube.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _neutube.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _neutube:
_neutube.SwigPyIterator_swigregister(SwigPyIterator)

class Double_Array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _neutube.Double_Array_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _neutube.Double_Array___nonzero__(self)

    def __bool__(self):
        return _neutube.Double_Array___bool__(self)

    def __len__(self):
        return _neutube.Double_Array___len__(self)

    def __getslice__(self, i, j):
        return _neutube.Double_Array___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _neutube.Double_Array___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _neutube.Double_Array___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _neutube.Double_Array___delitem__(self, *args)

    def __getitem__(self, *args):
        return _neutube.Double_Array___getitem__(self, *args)

    def __setitem__(self, *args):
        return _neutube.Double_Array___setitem__(self, *args)

    def pop(self):
        return _neutube.Double_Array_pop(self)

    def append(self, x):
        return _neutube.Double_Array_append(self, x)

    def empty(self):
        return _neutube.Double_Array_empty(self)

    def size(self):
        return _neutube.Double_Array_size(self)

    def swap(self, v):
        return _neutube.Double_Array_swap(self, v)

    def begin(self):
        return _neutube.Double_Array_begin(self)

    def end(self):
        return _neutube.Double_Array_end(self)

    def rbegin(self):
        return _neutube.Double_Array_rbegin(self)

    def rend(self):
        return _neutube.Double_Array_rend(self)

    def clear(self):
        return _neutube.Double_Array_clear(self)

    def get_allocator(self):
        return _neutube.Double_Array_get_allocator(self)

    def pop_back(self):
        return _neutube.Double_Array_pop_back(self)

    def erase(self, *args):
        return _neutube.Double_Array_erase(self, *args)

    def __init__(self, *args):
        _neutube.Double_Array_swiginit(self, _neutube.new_Double_Array(*args))

    def push_back(self, x):
        return _neutube.Double_Array_push_back(self, x)

    def front(self):
        return _neutube.Double_Array_front(self)

    def back(self):
        return _neutube.Double_Array_back(self)

    def assign(self, n, x):
        return _neutube.Double_Array_assign(self, n, x)

    def resize(self, *args):
        return _neutube.Double_Array_resize(self, *args)

    def insert(self, *args):
        return _neutube.Double_Array_insert(self, *args)

    def reserve(self, n):
        return _neutube.Double_Array_reserve(self, n)

    def capacity(self):
        return _neutube.Double_Array_capacity(self)
    __swig_destroy__ = _neutube.delete_Double_Array

# Register Double_Array in _neutube:
_neutube.Double_Array_swigregister(Double_Array)

class Byte_Array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _neutube.Byte_Array_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _neutube.Byte_Array___nonzero__(self)

    def __bool__(self):
        return _neutube.Byte_Array___bool__(self)

    def __len__(self):
        return _neutube.Byte_Array___len__(self)

    def __getslice__(self, i, j):
        return _neutube.Byte_Array___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _neutube.Byte_Array___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _neutube.Byte_Array___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _neutube.Byte_Array___delitem__(self, *args)

    def __getitem__(self, *args):
        return _neutube.Byte_Array___getitem__(self, *args)

    def __setitem__(self, *args):
        return _neutube.Byte_Array___setitem__(self, *args)

    def pop(self):
        return _neutube.Byte_Array_pop(self)

    def append(self, x):
        return _neutube.Byte_Array_append(self, x)

    def empty(self):
        return _neutube.Byte_Array_empty(self)

    def size(self):
        return _neutube.Byte_Array_size(self)

    def swap(self, v):
        return _neutube.Byte_Array_swap(self, v)

    def begin(self):
        return _neutube.Byte_Array_begin(self)

    def end(self):
        return _neutube.Byte_Array_end(self)

    def rbegin(self):
        return _neutube.Byte_Array_rbegin(self)

    def rend(self):
        return _neutube.Byte_Array_rend(self)

    def clear(self):
        return _neutube.Byte_Array_clear(self)

    def get_allocator(self):
        return _neutube.Byte_Array_get_allocator(self)

    def pop_back(self):
        return _neutube.Byte_Array_pop_back(self)

    def erase(self, *args):
        return _neutube.Byte_Array_erase(self, *args)

    def __init__(self, *args):
        _neutube.Byte_Array_swiginit(self, _neutube.new_Byte_Array(*args))

    def push_back(self, x):
        return _neutube.Byte_Array_push_back(self, x)

    def front(self):
        return _neutube.Byte_Array_front(self)

    def back(self):
        return _neutube.Byte_Array_back(self)

    def assign(self, n, x):
        return _neutube.Byte_Array_assign(self, n, x)

    def resize(self, *args):
        return _neutube.Byte_Array_resize(self, *args)

    def insert(self, *args):
        return _neutube.Byte_Array_insert(self, *args)

    def reserve(self, n):
        return _neutube.Byte_Array_reserve(self, n)

    def capacity(self):
        return _neutube.Byte_Array_capacity(self)
    __swig_destroy__ = _neutube.delete_Byte_Array

# Register Byte_Array in _neutube:
_neutube.Byte_Array_swigregister(Byte_Array)

class Char_Array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _neutube.Char_Array_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _neutube.Char_Array___nonzero__(self)

    def __bool__(self):
        return _neutube.Char_Array___bool__(self)

    def __len__(self):
        return _neutube.Char_Array___len__(self)

    def __getslice__(self, i, j):
        return _neutube.Char_Array___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _neutube.Char_Array___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _neutube.Char_Array___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _neutube.Char_Array___delitem__(self, *args)

    def __getitem__(self, *args):
        return _neutube.Char_Array___getitem__(self, *args)

    def __setitem__(self, *args):
        return _neutube.Char_Array___setitem__(self, *args)

    def pop(self):
        return _neutube.Char_Array_pop(self)

    def append(self, x):
        return _neutube.Char_Array_append(self, x)

    def empty(self):
        return _neutube.Char_Array_empty(self)

    def size(self):
        return _neutube.Char_Array_size(self)

    def swap(self, v):
        return _neutube.Char_Array_swap(self, v)

    def begin(self):
        return _neutube.Char_Array_begin(self)

    def end(self):
        return _neutube.Char_Array_end(self)

    def rbegin(self):
        return _neutube.Char_Array_rbegin(self)

    def rend(self):
        return _neutube.Char_Array_rend(self)

    def clear(self):
        return _neutube.Char_Array_clear(self)

    def get_allocator(self):
        return _neutube.Char_Array_get_allocator(self)

    def pop_back(self):
        return _neutube.Char_Array_pop_back(self)

    def erase(self, *args):
        return _neutube.Char_Array_erase(self, *args)

    def __init__(self, *args):
        _neutube.Char_Array_swiginit(self, _neutube.new_Char_Array(*args))

    def push_back(self, x):
        return _neutube.Char_Array_push_back(self, x)

    def front(self):
        return _neutube.Char_Array_front(self)

    def back(self):
        return _neutube.Char_Array_back(self)

    def assign(self, n, x):
        return _neutube.Char_Array_assign(self, n, x)

    def resize(self, *args):
        return _neutube.Char_Array_resize(self, *args)

    def insert(self, *args):
        return _neutube.Char_Array_insert(self, *args)

    def reserve(self, n):
        return _neutube.Char_Array_reserve(self, n)

    def capacity(self):
        return _neutube.Char_Array_capacity(self)
    __swig_destroy__ = _neutube.delete_Char_Array

# Register Char_Array in _neutube:
_neutube.Char_Array_swigregister(Char_Array)

class Point_Array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _neutube.Point_Array_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _neutube.Point_Array___nonzero__(self)

    def __bool__(self):
        return _neutube.Point_Array___bool__(self)

    def __len__(self):
        return _neutube.Point_Array___len__(self)

    def __getslice__(self, i, j):
        return _neutube.Point_Array___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _neutube.Point_Array___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _neutube.Point_Array___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _neutube.Point_Array___delitem__(self, *args)

    def __getitem__(self, *args):
        return _neutube.Point_Array___getitem__(self, *args)

    def __setitem__(self, *args):
        return _neutube.Point_Array___setitem__(self, *args)

    def pop(self):
        return _neutube.Point_Array_pop(self)

    def append(self, x):
        return _neutube.Point_Array_append(self, x)

    def empty(self):
        return _neutube.Point_Array_empty(self)

    def size(self):
        return _neutube.Point_Array_size(self)

    def swap(self, v):
        return _neutube.Point_Array_swap(self, v)

    def begin(self):
        return _neutube.Point_Array_begin(self)

    def end(self):
        return _neutube.Point_Array_end(self)

    def rbegin(self):
        return _neutube.Point_Array_rbegin(self)

    def rend(self):
        return _neutube.Point_Array_rend(self)

    def clear(self):
        return _neutube.Point_Array_clear(self)

    def get_allocator(self):
        return _neutube.Point_Array_get_allocator(self)

    def pop_back(self):
        return _neutube.Point_Array_pop_back(self)

    def erase(self, *args):
        return _neutube.Point_Array_erase(self, *args)

    def __init__(self, *args):
        _neutube.Point_Array_swiginit(self, _neutube.new_Point_Array(*args))

    def push_back(self, x):
        return _neutube.Point_Array_push_back(self, x)

    def front(self):
        return _neutube.Point_Array_front(self)

    def back(self):
        return _neutube.Point_Array_back(self)

    def assign(self, n, x):
        return _neutube.Point_Array_assign(self, n, x)

    def resize(self, *args):
        return _neutube.Point_Array_resize(self, *args)

    def insert(self, *args):
        return _neutube.Point_Array_insert(self, *args)

    def reserve(self, n):
        return _neutube.Point_Array_reserve(self, n)

    def capacity(self):
        return _neutube.Point_Array_capacity(self)
    __swig_destroy__ = _neutube.delete_Point_Array

# Register Point_Array in _neutube:
_neutube.Point_Array_swigregister(Point_Array)

class PStack(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    width = property(_neutube.PStack_width_get, _neutube.PStack_width_set)
    height = property(_neutube.PStack_height_get, _neutube.PStack_height_set)
    depth = property(_neutube.PStack_depth_get, _neutube.PStack_depth_set)
    array = property(_neutube.PStack_array_get, _neutube.PStack_array_set)

    def __init__(self):
        _neutube.PStack_swiginit(self, _neutube.new_PStack())
    __swig_destroy__ = _neutube.delete_PStack

# Register PStack in _neutube:
_neutube.PStack_swigregister(PStack)


def Python_Stack(stack):
    return _neutube.Python_Stack(stack)

def DeleteStackObject(stack):
    return _neutube.DeleteStackObject(stack)

def PrintDoubleArray(array):
    return _neutube.PrintDoubleArray(array)

def PrintCharArray(array):
    return _neutube.PrintCharArray(array)

def PrintString(str):
    return _neutube.PrintString(str)

def CharArrayTest():
    return _neutube.CharArrayTest()

def Read_Stack_U(filePath):
    return _neutube.Read_Stack_U(filePath)

def Write_Stack_P(stack, filePath):
    return _neutube.Write_Stack_P(stack, filePath)

def Make_Stack(kind, width, height, depth):
    return _neutube.Make_Stack(kind, width, height, depth)

def Kill_Stack(stack):
    return _neutube.Kill_Stack(stack)

def Stack_Width(stack):
    return _neutube.Stack_Width(stack)

def Stack_Height(stack):
    return _neutube.Stack_Height(stack)

def Stack_Depth(stack):
    return _neutube.Stack_Depth(stack)

def Stack_Kind(stack):
    return _neutube.Stack_Kind(stack)

def Stack_Plane_Area(stack):
    return _neutube.Stack_Plane_Area(stack)

def Stack_Volume(stack):
    return _neutube.Stack_Volume(stack)

def Stack_Set_Width(stack, width):
    return _neutube.Stack_Set_Width(stack, width)

def Stack_Set_Height(stack, height):
    return _neutube.Stack_Set_Height(stack, height)

def Stack_Set_Depth(stack, depth):
    return _neutube.Stack_Set_Depth(stack, depth)

def Stack_Set_Kind(stack, kind):
    return _neutube.Stack_Set_Kind(stack, kind)

def Stack_Set_Attribute(stack, width, height, depth, kind):
    return _neutube.Stack_Set_Attribute(stack, width, height, depth, kind)

def Stack_Channel_Number(stack):
    return _neutube.Stack_Channel_Number(stack)

def Stack_Voxel_Number(stack):
    return _neutube.Stack_Voxel_Number(stack)

def Stack_Voxel_Bsize(stack):
    return _neutube.Stack_Voxel_Bsize(stack)

def Stack_Array_Bsize(stack):
    return _neutube.Stack_Array_Bsize(stack)

def Stack_Contain_Point(stack, x, y, z):
    return _neutube.Stack_Contain_Point(stack, x, y, z)

def Stack_Is_Empty(stack):
    return _neutube.Stack_Is_Empty(stack)

def Stack_Is_Dark(stack):
    return _neutube.Stack_Is_Dark(stack)
class ZStack(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _neutube.ZStack_swiginit(self, _neutube.new_ZStack(*args))
    __swig_destroy__ = _neutube.delete_ZStack
    SINGLE_VOXEL = _neutube.ZStack_SINGLE_VOXEL
    SINGLE_PLANE = _neutube.ZStack_SINGLE_PLANE
    SINGLE_ROW = _neutube.ZStack_SINGLE_ROW
    SINGLE_CHANNEL = _neutube.ZStack_SINGLE_CHANNEL
    WHOLE_DATA = _neutube.ZStack_WHOLE_DATA

    def mc_stack(self, *args):
        return _neutube.ZStack_mc_stack(self, *args)

    def data(self, *args):
        return _neutube.ZStack_data(self, *args)

    def setData(self, *args):
        return _neutube.ZStack_setData(self, *args)

    def consume(self, *args):
        return _neutube.ZStack_consume(self, *args)

    def c_stack(self, *args):
        return _neutube.ZStack_c_stack(self, *args)

    def singleChannelStack(self, *args):
        return _neutube.ZStack_singleChannelStack(self, *args)

    def getSingleChannel(self, c):
        return _neutube.ZStack_getSingleChannel(self, c)

    def width(self):
        return _neutube.ZStack_width(self)

    def height(self):
        return _neutube.ZStack_height(self)

    def depth(self):
        return _neutube.ZStack_depth(self)

    def kind(self):
        return _neutube.ZStack_kind(self)

    def channelNumber(self):
        return _neutube.ZStack_channelNumber(self)
    MC_STACK = _neutube.ZStack_MC_STACK
    SINGLE_CHANNEL_VIEW = _neutube.ZStack_SINGLE_CHANNEL_VIEW

    def getByteNumber(self, *args):
        return _neutube.ZStack_getByteNumber(self, *args)

    def getVoxelNumber(self, *args):
        return _neutube.ZStack_getVoxelNumber(self, *args)

    def value(self, *args):
        return _neutube.ZStack_value(self, *args)

    def getIntValue8WithXCheckOnly(self, x, y, z, c=0):
        return _neutube.ZStack_getIntValue8WithXCheckOnly(self, x, y, z, c)

    def getIntValueLocal(self, x, y, z, c=0):
        return _neutube.ZStack_getIntValueLocal(self, x, y, z, c)

    def getIntValue(self, *args):
        return _neutube.ZStack_getIntValue(self, *args)

    def setIntValue(self, x, y, z, c, v):
        return _neutube.ZStack_setIntValue(self, x, y, z, c, v)

    def addIntValue(self, x, y, z, c, v):
        return _neutube.ZStack_addIntValue(self, x, y, z, c, v)

    def array8(self, *args):
        return _neutube.ZStack_array8(self, *args)

    def array16(self, *args):
        return _neutube.ZStack_array16(self, *args)

    def array32(self, *args):
        return _neutube.ZStack_array32(self, *args)

    def array64(self, *args):
        return _neutube.ZStack_array64(self, *args)

    def arrayc(self, *args):
        return _neutube.ZStack_arrayc(self, *args)

    def value8(self, *args):
        return _neutube.ZStack_value8(self, *args)

    def isEmpty(self):
        return _neutube.ZStack_isEmpty(self)

    def isVirtual(self):
        return _neutube.ZStack_isVirtual(self)

    def hasData(self):
        return _neutube.ZStack_hasData(self)

    @staticmethod
    def makeMcStack(stack1, stack2, stack3):
        return _neutube.ZStack_makeMcStack(stack1, stack2, stack3)

    def sourcePath(self):
        return _neutube.ZStack_sourcePath(self)

    def min(self, *args):
        return _neutube.ZStack_min(self, *args)

    def max(self, *args):
        return _neutube.ZStack_max(self, *args)

    def contains(self, *args):
        return _neutube.ZStack_contains(self, *args)

    def containsRaw(self, *args):
        return _neutube.ZStack_containsRaw(self, *args)

    def reshape(self, width, height, depth):
        return _neutube.ZStack_reshape(self, width, height, depth)

    def autoThreshold(self, ch=0):
        return _neutube.ZStack_autoThreshold(self, ch)

    def color(self, *args):
        return _neutube.ZStack_color(self, *args)

    def equalColor(self, *args):
        return _neutube.ZStack_equalColor(self, *args)

    def setValue(self, *args):
        return _neutube.ZStack_setValue(self, *args)

    def setZero(self):
        return _neutube.ZStack_setZero(self)

    def setOne(self):
        return _neutube.ZStack_setOne(self)

    def maxIntensityDepth(self, x, y, c=0):
        return _neutube.ZStack_maxIntensityDepth(self, x, y, c)

    def isThresholdable(self):
        return _neutube.ZStack_isThresholdable(self)

    def isTracable(self):
        return _neutube.ZStack_isTracable(self)

    def isSwc(self):
        return _neutube.ZStack_isSwc(self)

    def getDataPointer(self, *args):
        return _neutube.ZStack_getDataPointer(self, *args)

    def printInfo(self):
        return _neutube.ZStack_printInfo(self)

    def clone(self):
        return _neutube.ZStack_clone(self)

    def source(self):
        return _neutube.ZStack_source(self)

    def deprecateDependent(self, component):
        return _neutube.ZStack_deprecateDependent(self, component)

    def deprecateSingleChannelView(self, channel):
        return _neutube.ZStack_deprecateSingleChannelView(self, channel)

    def deprecate(self, component):
        return _neutube.ZStack_deprecate(self, component)

    def isDeprecated(self, component):
        return _neutube.ZStack_isDeprecated(self, component)

    def isSingleChannelViewDeprecated(self, channel):
        return _neutube.ZStack_isSingleChannelViewDeprecated(self, channel)

    def clear(self):
        return _neutube.ZStack_clear(self)

    def removeChannel(self, c=0):
        return _neutube.ZStack_removeChannel(self, c)

    def load(self, *args):
        return _neutube.ZStack_load(self, *args)

    def save(self, filepath):
        return _neutube.ZStack_save(self, filepath)

    def setSource(self, *args):
        return _neutube.ZStack_setSource(self, *args)

    @staticmethod
    def getChannelNumber(filepath):
        return _neutube.ZStack_getChannelNumber(filepath)

    def rawChannelData(self, *args):
        return _neutube.ZStack_rawChannelData(self, *args)

    def projection(self, *args):
        return _neutube.ZStack_projection(self, *args)

    def bcAdjustHint(self, scale, offset, c=0):
        return _neutube.ZStack_bcAdjustHint(self, scale, offset, c)

    def isBinary(self):
        return _neutube.ZStack_isBinary(self)

    def updateFromSource(self):
        return _neutube.ZStack_updateFromSource(self)

    def hasSameValue(self, *args):
        return _neutube.ZStack_hasSameValue(self, *args)

    def createSubstack(self, selected):
        return _neutube.ZStack_createSubstack(self, selected)

    def averageIntensity(self, mask):
        return _neutube.ZStack_averageIntensity(self, mask)

    def loadValue(self, *args):
        return _neutube.ZStack_loadValue(self, *args)

    def setOffset(self, *args):
        return _neutube.ZStack_setOffset(self, *args)

    def setZOffset(self, z):
        return _neutube.ZStack_setZOffset(self, z)

    def getOffset(self, *args):
        return _neutube.ZStack_getOffset(self, *args)

    def translate(self, *args):
        return _neutube.ZStack_translate(self, *args)

    def hasOffset(self):
        return _neutube.ZStack_hasOffset(self)

    def paste(self, dst, valueIgnored=-1, alpha=1.0):
        return _neutube.ZStack_paste(self, dst, valueIgnored, alpha)

    def getBoundBox(self, *args):
        return _neutube.ZStack_getBoundBox(self, *args)

    def setBlockValue(self, x0, y0, z0, stack):
        return _neutube.ZStack_setBlockValue(self, x0, y0, z0, stack)

    def binarize(self, threshold=0):
        return _neutube.ZStack_binarize(self, threshold)

    def bwsolid(self):
        return _neutube.ZStack_bwsolid(self)

    def bwperim(self):
        return _neutube.ZStack_bwperim(self)

    def enhanceLine(self):
        return _neutube.ZStack_enhanceLine(self)

    def extractChannel(self, c):
        return _neutube.ZStack_extractChannel(self, c)

    def copyChannel(self, c):
        return _neutube.ZStack_copyChannel(self, c)

    def watershed(self, c=0):
        return _neutube.ZStack_watershed(self, c)

    def downsampleMax(self, xintv, yintv, zintv):
        return _neutube.ZStack_downsampleMax(self, xintv, yintv, zintv)

    def downsampleMin(self, xintv, yintv, zintv):
        return _neutube.ZStack_downsampleMin(self, xintv, yintv, zintv)

    def crop(self, cuboid):
        return _neutube.ZStack_crop(self, cuboid)

    def makeCrop(self, cuboid):
        return _neutube.ZStack_makeCrop(self, cuboid)

    def swapData(self, stack):
        return _neutube.ZStack_swapData(self, stack)

    def initChannelColors(self):
        return _neutube.ZStack_initChannelColors(self)

# Register ZStack in _neutube:
_neutube.ZStack_swigregister(ZStack)

def ZStack_makeMcStack(stack1, stack2, stack3):
    return _neutube.ZStack_makeMcStack(stack1, stack2, stack3)

def ZStack_getChannelNumber(filepath):
    return _neutube.ZStack_getChannelNumber(filepath)

class ZStackObject(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _neutube.delete_ZStackObject
    TYPE_UNIDENTIFIED = _neutube.ZStackObject_TYPE_UNIDENTIFIED
    TYPE_SWC = _neutube.ZStackObject_TYPE_SWC
    TYPE_PUNCTUM = _neutube.ZStackObject_TYPE_PUNCTUM
    TYPE_OBJ3D = _neutube.ZStackObject_TYPE_OBJ3D
    TYPE_STROKE = _neutube.ZStackObject_TYPE_STROKE
    TYPE_LOCSEG_CHAIN = _neutube.ZStackObject_TYPE_LOCSEG_CHAIN
    TYPE_CONN = _neutube.ZStackObject_TYPE_CONN
    TYPE_OBJECT3D_SCAN = _neutube.ZStackObject_TYPE_OBJECT3D_SCAN
    TYPE_SPARSE_OBJECT = _neutube.ZStackObject_TYPE_SPARSE_OBJECT
    TYPE_CIRCLE = _neutube.ZStackObject_TYPE_CIRCLE
    TYPE_STACK_BALL = _neutube.ZStackObject_TYPE_STACK_BALL
    TYPE_STACK_PATCH = _neutube.ZStackObject_TYPE_STACK_PATCH
    TYPE_RECT2D = _neutube.ZStackObject_TYPE_RECT2D
    TYPE_DVID_TILE = _neutube.ZStackObject_TYPE_DVID_TILE
    TYPE_DVID_GRAY_SLICE = _neutube.ZStackObject_TYPE_DVID_GRAY_SLICE
    TYPE_DVID_TILE_ENSEMBLE = _neutube.ZStackObject_TYPE_DVID_TILE_ENSEMBLE
    TYPE_DVID_LABEL_SLICE = _neutube.ZStackObject_TYPE_DVID_LABEL_SLICE
    TYPE_DVID_SPARSE_STACK = _neutube.ZStackObject_TYPE_DVID_SPARSE_STACK
    TYPE_DVID_SPARSEVOL_SLICE = _neutube.ZStackObject_TYPE_DVID_SPARSEVOL_SLICE
    TYPE_STACK = _neutube.ZStackObject_TYPE_STACK
    TYPE_SWC_NODE = _neutube.ZStackObject_TYPE_SWC_NODE
    TYPE_3D_GRAPH = _neutube.ZStackObject_TYPE_3D_GRAPH
    TYPE_PUNCTA = _neutube.ZStackObject_TYPE_PUNCTA
    TYPE_FLYEM_BOOKMARK = _neutube.ZStackObject_TYPE_FLYEM_BOOKMARK
    TYPE_INT_CUBOID = _neutube.ZStackObject_TYPE_INT_CUBOID
    TYPE_LINE_SEGMENT = _neutube.ZStackObject_TYPE_LINE_SEGMENT
    TYPE_SLICED_PUNCTA = _neutube.ZStackObject_TYPE_SLICED_PUNCTA
    TYPE_DVID_SYNAPSE = _neutube.ZStackObject_TYPE_DVID_SYNAPSE
    TYPE_DVID_SYNAPE_ENSEMBLE = _neutube.ZStackObject_TYPE_DVID_SYNAPE_ENSEMBLE
    TYPE_DVID_ANNOTATION = _neutube.ZStackObject_TYPE_DVID_ANNOTATION
    TYPE_FLYEM_TODO_ITEM = _neutube.ZStackObject_TYPE_FLYEM_TODO_ITEM
    TYPE_FLYEM_TODO_LIST = _neutube.ZStackObject_TYPE_FLYEM_TODO_LIST
    BLUE = _neutube.ZStackObject_BLUE
    GREEN = _neutube.ZStackObject_GREEN
    RED = _neutube.ZStackObject_RED
    ALPHA = _neutube.ZStackObject_ALPHA
    NORMAL = _neutube.ZStackObject_NORMAL
    SOLID = _neutube.ZStackObject_SOLID
    BOUNDARY = _neutube.ZStackObject_BOUNDARY
    SKELETON = _neutube.ZStackObject_SKELETON
    TARGET_STACK_CANVAS = _neutube.ZStackObject_TARGET_STACK_CANVAS
    TARGET_OBJECT_CANVAS = _neutube.ZStackObject_TARGET_OBJECT_CANVAS
    TARGET_WIDGET = _neutube.ZStackObject_TARGET_WIDGET
    TARGET_TILE_CANVAS = _neutube.ZStackObject_TARGET_TILE_CANVAS
    TARGET_3D_ONLY = _neutube.ZStackObject_TARGET_3D_ONLY
    DISPLAY_SLICE_PROJECTION = _neutube.ZStackObject_DISPLAY_SLICE_PROJECTION
    DISPLAY_SLICE_SINGLE = _neutube.ZStackObject_DISPLAY_SLICE_SINGLE

    def className(self):
        return _neutube.ZStackObject_className(self)

    def setSelected(self, selected):
        return _neutube.ZStackObject_setSelected(self, selected)

    def display(self, *args):
        return _neutube.ZStackObject_display(self, *args)

    def isVisible(self):
        return _neutube.ZStackObject_isVisible(self)

    def setVisible(self, visible):
        return _neutube.ZStackObject_setVisible(self, visible)

    def toggleVisible(self):
        return _neutube.ZStackObject_toggleVisible(self)

    def setDisplayStyle(self, style):
        return _neutube.ZStackObject_setDisplayStyle(self, style)

    def displayStyle(self):
        return _neutube.ZStackObject_displayStyle(self)

    def getTarget(self):
        return _neutube.ZStackObject_getTarget(self)

    def setTarget(self, target):
        return _neutube.ZStackObject_setTarget(self, target)

    def isSliceVisible(self, z, axis):
        return _neutube.ZStackObject_isSliceVisible(self, z, axis)

    def hit(self, *args):
        return _neutube.ZStackObject_hit(self, *args)

    def getHitPoint(self):
        return _neutube.ZStackObject_getHitPoint(self)

    def getBoundBox(self, box):
        return _neutube.ZStackObject_getBoundBox(self, box)

    def getColor(self):
        return _neutube.ZStackObject_getColor(self)

    def setColor(self, *args):
        return _neutube.ZStackObject_setColor(self, *args)

    def setAlpha(self, alpha):
        return _neutube.ZStackObject_setAlpha(self, alpha)

    def getAlpha(self):
        return _neutube.ZStackObject_getAlpha(self)

    def getAlphaF(self):
        return _neutube.ZStackObject_getAlphaF(self)

    def getRedF(self):
        return _neutube.ZStackObject_getRedF(self)

    def getGreenF(self):
        return _neutube.ZStackObject_getGreenF(self)

    def getBlueF(self):
        return _neutube.ZStackObject_getBlueF(self)

    def isOpaque(self):
        return _neutube.ZStackObject_isOpaque(self)

    @staticmethod
    def setDefaultPenWidth(width):
        return _neutube.ZStackObject_setDefaultPenWidth(width)

    @staticmethod
    def getDefaultPenWidth():
        return _neutube.ZStackObject_getDefaultPenWidth()

    def getPenWidth(self):
        return _neutube.ZStackObject_getPenWidth(self)

    def useCosmeticPen(self, state):
        return _neutube.ZStackObject_useCosmeticPen(self, state)

    def getSource(self):
        return _neutube.ZStackObject_getSource(self)

    def setSource(self, source):
        return _neutube.ZStackObject_setSource(self, source)

    @staticmethod
    def fromSameSource(*args):
        return _neutube.ZStackObject_fromSameSource(*args)

    def getObjectId(self):
        return _neutube.ZStackObject_getObjectId(self)

    def setObjectId(self, id):
        return _neutube.ZStackObject_setObjectId(self, id)

    @staticmethod
    def hasSameId(*args):
        return _neutube.ZStackObject_hasSameId(*args)

    def getObjectClass(self):
        return _neutube.ZStackObject_getObjectClass(self)

    def setObjectClass(self, id):
        return _neutube.ZStackObject_setObjectClass(self, id)

    def setZScale(self, scale):
        return _neutube.ZStackObject_setZScale(self, scale)

    def getZOrder(self):
        return _neutube.ZStackObject_getZOrder(self)

    def setZOrder(self, order):
        return _neutube.ZStackObject_setZOrder(self, order)

    def getType(self):
        return _neutube.ZStackObject_getType(self)

    @staticmethod
    def GetType():
        return _neutube.ZStackObject_GetType()

    def getRole(self):
        return _neutube.ZStackObject_getRole(self)

    def hasRole(self, *args):
        return _neutube.ZStackObject_hasRole(self, *args)

    def setRole(self, role):
        return _neutube.ZStackObject_setRole(self, role)

    def addRole(self, role):
        return _neutube.ZStackObject_addRole(self, role)

    def isSelectable(self):
        return _neutube.ZStackObject_isSelectable(self)

    def setSelectable(self, state):
        return _neutube.ZStackObject_setSelectable(self, state)

    def isHittable(self):
        return _neutube.ZStackObject_isHittable(self)

    def setHittable(self, state):
        return _neutube.ZStackObject_setHittable(self, state)

    def setHitPoint(self, pt):
        return _neutube.ZStackObject_setHitPoint(self, pt)

    def isProjectionVisible(self):
        return _neutube.ZStackObject_isProjectionVisible(self)

    def setProjectionVisible(self, visible):
        return _neutube.ZStackObject_setProjectionVisible(self, visible)

    def addVisualEffect(self, ve):
        return _neutube.ZStackObject_addVisualEffect(self, ve)

    def removeVisualEffect(self, ve):
        return _neutube.ZStackObject_removeVisualEffect(self, ve)

    def setVisualEffect(self, ve):
        return _neutube.ZStackObject_setVisualEffect(self, ve)

    def hasVisualEffect(self, ve):
        return _neutube.ZStackObject_hasVisualEffect(self, ve)

    def getSliceAxis(self):
        return _neutube.ZStackObject_getSliceAxis(self)

    def setSliceAxis(self, axis):
        return _neutube.ZStackObject_setSliceAxis(self, axis)

    @staticmethod
    def isEmptyTree(obj):
        return _neutube.ZStackObject_isEmptyTree(obj)

    @staticmethod
    def isSameSource(s1, s2):
        return _neutube.ZStackObject_isSameSource(s1, s2)

    @staticmethod
    def isSameClass(s1, s2):
        return _neutube.ZStackObject_isSameClass(s1, s2)

    @staticmethod
    def isSelected(*args):
        return _neutube.ZStackObject_isSelected(*args)

# Register ZStackObject in _neutube:
_neutube.ZStackObject_swigregister(ZStackObject)

def ZStackObject_setDefaultPenWidth(width):
    return _neutube.ZStackObject_setDefaultPenWidth(width)

def ZStackObject_getDefaultPenWidth():
    return _neutube.ZStackObject_getDefaultPenWidth()

def ZStackObject_fromSameSource(*args):
    return _neutube.ZStackObject_fromSameSource(*args)

def ZStackObject_hasSameId(*args):
    return _neutube.ZStackObject_hasSameId(*args)

def ZStackObject_GetType():
    return _neutube.ZStackObject_GetType()

def ZStackObject_isEmptyTree(obj):
    return _neutube.ZStackObject_isEmptyTree(obj)

def ZStackObject_isSameSource(s1, s2):
    return _neutube.ZStackObject_isSameSource(s1, s2)

def ZStackObject_isSameClass(s1, s2):
    return _neutube.ZStackObject_isSameClass(s1, s2)

def ZStackObject_isSelected(*args):
    return _neutube.ZStackObject_isSelected(*args)

class ZSwcTree(ZStackObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    CLEAN_ALL = _neutube.ZSwcTree_CLEAN_ALL
    FREE_WRAPPER = _neutube.ZSwcTree_FREE_WRAPPER
    LEAVE_ALONE = _neutube.ZSwcTree_LEAVE_ALONE
    SWC_NODE = _neutube.ZSwcTree_SWC_NODE
    WHOLE_TREE = _neutube.ZSwcTree_WHOLE_TREE
    SWC_BRANCH = _neutube.ZSwcTree_SWC_BRANCH
    NODE_STATE_COSMETIC = _neutube.ZSwcTree_NODE_STATE_COSMETIC
    STRUCT_CLOSED_CURVE = _neutube.ZSwcTree_STRUCT_CLOSED_CURVE
    STRUCT_NORMAL = _neutube.ZSwcTree_STRUCT_NORMAL
    OPERATION_NULL = _neutube.ZSwcTree_OPERATION_NULL
    OPERATION_DELETE_NODE = _neutube.ZSwcTree_OPERATION_DELETE_NODE
    OPERATION_SELECT_ALL_NODE = _neutube.ZSwcTree_OPERATION_SELECT_ALL_NODE
    OPERATION_MOVE_NODE_LEFT = _neutube.ZSwcTree_OPERATION_MOVE_NODE_LEFT
    OPERATION_MOVE_NODE_LEFT_FAST = _neutube.ZSwcTree_OPERATION_MOVE_NODE_LEFT_FAST
    OPERATION_MOVE_NODE_RIGHT = _neutube.ZSwcTree_OPERATION_MOVE_NODE_RIGHT
    OPERATION_MOVE_NODE_RIGHT_FAST = _neutube.ZSwcTree_OPERATION_MOVE_NODE_RIGHT_FAST
    OPERATION_MOVE_NODE_UP = _neutube.ZSwcTree_OPERATION_MOVE_NODE_UP
    OPERATION_MOVE_NODE_UP_FAST = _neutube.ZSwcTree_OPERATION_MOVE_NODE_UP_FAST
    OPERATION_MOVE_NODE_DOWN = _neutube.ZSwcTree_OPERATION_MOVE_NODE_DOWN
    OPERATION_MOVE_NODE_DOWN_FAST = _neutube.ZSwcTree_OPERATION_MOVE_NODE_DOWN_FAST
    OPERATION_ADD_NODE = _neutube.ZSwcTree_OPERATION_ADD_NODE
    OPERATION_INCREASE_NODE_SIZE = _neutube.ZSwcTree_OPERATION_INCREASE_NODE_SIZE
    OPERATION_DECREASE_NODE_SIZE = _neutube.ZSwcTree_OPERATION_DECREASE_NODE_SIZE
    OPERATION_CONNECT_NODE = _neutube.ZSwcTree_OPERATION_CONNECT_NODE
    OPERATION_CONNECT_NODE_SMART = _neutube.ZSwcTree_OPERATION_CONNECT_NODE_SMART
    OPERATION_BREAK_NODE = _neutube.ZSwcTree_OPERATION_BREAK_NODE
    OPERATION_CONNECT_ISOLATE = _neutube.ZSwcTree_OPERATION_CONNECT_ISOLATE
    OPERATION_ZOOM_TO_SELECTED_NODE = _neutube.ZSwcTree_OPERATION_ZOOM_TO_SELECTED_NODE
    OPERATION_INSERT_NODE = _neutube.ZSwcTree_OPERATION_INSERT_NODE
    OPERATION_MOVE_NODE = _neutube.ZSwcTree_OPERATION_MOVE_NODE
    OPERATION_RESET_BRANCH_POINT = _neutube.ZSwcTree_OPERATION_RESET_BRANCH_POINT
    OPERATION_CHANGE_NODE_FACUS = _neutube.ZSwcTree_OPERATION_CHANGE_NODE_FACUS
    OPERATION_SET_AS_ROOT = _neutube.ZSwcTree_OPERATION_SET_AS_ROOT
    OPERATION_EXTEND_NODE = _neutube.ZSwcTree_OPERATION_EXTEND_NODE
    OPERATION_SELECT = _neutube.ZSwcTree_OPERATION_SELECT
    OPERATION_SELECT_CONNECTION = _neutube.ZSwcTree_OPERATION_SELECT_CONNECTION
    OPERATION_SELECT_FLOOD = _neutube.ZSwcTree_OPERATION_SELECT_FLOOD

    def __init__(self):
        _neutube.ZSwcTree_swiginit(self, _neutube.new_ZSwcTree())
    __swig_destroy__ = _neutube.delete_ZSwcTree

    def className(self):
        return _neutube.ZSwcTree_className(self)

    @staticmethod
    def GetType():
        return _neutube.ZSwcTree_GetType()

    def setData(self, *args):
        return _neutube.ZSwcTree_setData(self, *args)

    def setDataFromNode(self, *args):
        return _neutube.ZSwcTree_setDataFromNode(self, *args)

    def setDataFromNodeRoot(self, *args):
        return _neutube.ZSwcTree_setDataFromNodeRoot(self, *args)

    def clone(self):
        return _neutube.ZSwcTree_clone(self)

    def cloneData(self):
        return _neutube.ZSwcTree_cloneData(self)

    def hasData(self):
        return _neutube.ZSwcTree_hasData(self)

    def data(self):
        return _neutube.ZSwcTree_data(self)

    def root(self):
        return _neutube.ZSwcTree_root(self)

    def isEmpty(self):
        return _neutube.ZSwcTree_isEmpty(self)

    def hasRegularNode(self):
        return _neutube.ZSwcTree_hasRegularNode(self)

    def isValid(self):
        return _neutube.ZSwcTree_isValid(self)

    def isForest(self):
        return _neutube.ZSwcTree_isForest(self)

    def display(self, painter, slice, option, axis):
        return _neutube.ZSwcTree_display(self, painter, slice, option, axis)

    def save(self, *args):
        return _neutube.ZSwcTree_save(self, *args)

    def load(self, *args):
        return _neutube.ZSwcTree_load(self, *args)

    def loadFromBuffer(self, buffer):
        return _neutube.ZSwcTree_loadFromBuffer(self, buffer)

    def isIdConsistent(self):
        return _neutube.ZSwcTree_isIdConsistent(self)

    def isIdValid(self):
        return _neutube.ZSwcTree_isIdValid(self)

    def swcFprint(self, fp, start_id=0, parent_id=-1, z_scale=1.0):
        return _neutube.ZSwcTree_swcFprint(self, fp, start_id, parent_id, z_scale)

    def swcExport(self, filePath):
        return _neutube.ZSwcTree_swcExport(self, filePath)

    def _print(self, *args):
        return _neutube.ZSwcTree__print(self, *args)

    def toString(self, *args):
        return _neutube.ZSwcTree_toString(self, *args)

    def saveAsLocsegChains(self, prefix, startNum):
        return _neutube.ZSwcTree_saveAsLocsegChains(self, prefix, startNum)

    def contains(self, tn):
        return _neutube.ZSwcTree_contains(self, tn)

    def regularRootNumber(self):
        return _neutube.ZSwcTree_regularRootNumber(self)

    def addRegularRoot(self, tn):
        return _neutube.ZSwcTree_addRegularRoot(self, tn)

    def maxLabelNode(self):
        return _neutube.ZSwcTree_maxLabelNode(self)
    DEPTH_FIRST_ARRAY = _neutube.ZSwcTree_DEPTH_FIRST_ARRAY
    BREADTH_FIRST_ARRAY = _neutube.ZSwcTree_BREADTH_FIRST_ARRAY
    LEAF_ARRAY = _neutube.ZSwcTree_LEAF_ARRAY
    TERMINAL_ARRAY = _neutube.ZSwcTree_TERMINAL_ARRAY
    BRANCH_POINT_ARRAY = _neutube.ZSwcTree_BRANCH_POINT_ARRAY
    Z_SORTED_ARRAY = _neutube.ZSwcTree_Z_SORTED_ARRAY
    ID_SORTED_ARRAY = _neutube.ZSwcTree_ID_SORTED_ARRAY
    BOUND_BOX = _neutube.ZSwcTree_BOUND_BOX
    ALL_COMPONENT = _neutube.ZSwcTree_ALL_COMPONENT

    def isDeprecated(self, component):
        return _neutube.ZSwcTree_isDeprecated(self, component)

    def deprecateDependent(self, component):
        return _neutube.ZSwcTree_deprecateDependent(self, component)

    def deprecate(self, component):
        return _neutube.ZSwcTree_deprecate(self, component)

    def addComment(self, comment):
        return _neutube.ZSwcTree_addComment(self, comment)

    def size(self, *args):
        return _neutube.ZSwcTree_size(self, *args)

    def updateIterator(self, *args):
        return _neutube.ZSwcTree_updateIterator(self, *args)

    def begin(self, *args):
        return _neutube.ZSwcTree_begin(self, *args)

    def end(self, *args):
        return _neutube.ZSwcTree_end(self, *args)

    def next(self, *args):
        return _neutube.ZSwcTree_next(self, *args)

    def labelBranch(self, x, y, z, thre):
        return _neutube.ZSwcTree_labelBranch(self, x, y, z, thre)

    def labelBranchLevel(self, rootType=-1):
        return _neutube.ZSwcTree_labelBranchLevel(self, rootType)

    def labelBranchLevelFromLeaf(self):
        return _neutube.ZSwcTree_labelBranchLevelFromLeaf(self)

    def boundBox(self, corner):
        return _neutube.ZSwcTree_boundBox(self, corner)

    def getBoundBox(self, *args):
        return _neutube.ZSwcTree_getBoundBox(self, *args)

    @staticmethod
    def CreateCuboidSwc(box, radius=1.0):
        return _neutube.ZSwcTree_CreateCuboidSwc(box, radius)

    def createBoundBoxSwc(self, margin=0.0):
        return _neutube.ZSwcTree_createBoundBoxSwc(self, margin)

    def hitTest(self, *args):
        return _neutube.ZSwcTree_hitTest(self, *args)

    def hit(self, *args):
        return _neutube.ZSwcTree_hit(self, *args)

    def selectNode(self, tn, appending):
        return _neutube.ZSwcTree_selectNode(self, tn, appending)

    def deselectNode(self, tn):
        return _neutube.ZSwcTree_deselectNode(self, tn)

    def selectAllNode(self):
        return _neutube.ZSwcTree_selectAllNode(self)

    def deselectAllNode(self):
        return _neutube.ZSwcTree_deselectAllNode(self)

    def inverseSelection(self):
        return _neutube.ZSwcTree_inverseSelection(self)

    def recordSelection(self):
        return _neutube.ZSwcTree_recordSelection(self)

    def processSelection(self):
        return _neutube.ZSwcTree_processSelection(self)

    def selectHitNode(self, appending):
        return _neutube.ZSwcTree_selectHitNode(self, appending)

    def deselectHitNode(self):
        return _neutube.ZSwcTree_deselectHitNode(self)

    def selectNodeConnection(self, seed):
        return _neutube.ZSwcTree_selectNodeConnection(self, seed)

    def selectNodeFloodFilling(self, seed):
        return _neutube.ZSwcTree_selectNodeFloodFilling(self, seed)

    def selectHitNodeConnection(self):
        return _neutube.ZSwcTree_selectHitNodeConnection(self)

    def selectHitNodeFloodFilling(self):
        return _neutube.ZSwcTree_selectHitNodeFloodFilling(self)

    def selectNeighborNode(self):
        return _neutube.ZSwcTree_selectNeighborNode(self)

    def selectConnectedNode(self):
        return _neutube.ZSwcTree_selectConnectedNode(self)

    def selectUpstreamNode(self):
        return _neutube.ZSwcTree_selectUpstreamNode(self)

    def selectDownstreamNode(self):
        return _neutube.ZSwcTree_selectDownstreamNode(self)

    def selectBranchNode(self):
        return _neutube.ZSwcTree_selectBranchNode(self)

    def selectSmallSubtree(self, maxLength):
        return _neutube.ZSwcTree_selectSmallSubtree(self, maxLength)

    def getSelectedNode(self):
        return _neutube.ZSwcTree_getSelectedNode(self)

    def hasSelectedNode(self):
        return _neutube.ZSwcTree_hasSelectedNode(self)

    def isNodeSelected(self, tn):
        return _neutube.ZSwcTree_isNodeSelected(self, tn)

    def getNodeSelector(self):
        return _neutube.ZSwcTree_getNodeSelector(self)

    def getHitNode(self):
        return _neutube.ZSwcTree_getHitNode(self)

    def setHitNode(self, tn):
        return _neutube.ZSwcTree_setHitNode(self, tn)

    def toSvgFile(self, filePath):
        return _neutube.ZSwcTree_toSvgFile(self, filePath)

    def translateRootTo(self, x, y, z):
        return _neutube.ZSwcTree_translateRootTo(self, x, y, z)

    def rescale(self, *args):
        return _neutube.ZSwcTree_rescale(self, *args)

    def rescaleRadius(self, scale, startdepth, enddepth):
        return _neutube.ZSwcTree_rescaleRadius(self, scale, startdepth, enddepth)

    def changeRadius(self, dr, scale):
        return _neutube.ZSwcTree_changeRadius(self, dr, scale)

    def swcNodeDepth(self, tn):
        return _neutube.ZSwcTree_swcNodeDepth(self, tn)

    def reduceNodeNumber(self, lengthThre):
        return _neutube.ZSwcTree_reduceNodeNumber(self, lengthThre)

    def distanceTo(self, *args):
        return _neutube.ZSwcTree_distanceTo(self, *args)

    def toSwcTreeArray(self):
        return _neutube.ZSwcTree_toSwcTreeArray(self)

    def resortId(self):
        return _neutube.ZSwcTree_resortId(self)

    def flipY(self, height):
        return _neutube.ZSwcTree_flipY(self, height)

    def removeRedundantBranch(self, redundacyThreshold):
        return _neutube.ZSwcTree_removeRedundantBranch(self, redundacyThreshold)

    def computeRedundancy(self, leaf):
        return _neutube.ZSwcTree_computeRedundancy(self, leaf)

    def removeBranch(self, tn):
        return _neutube.ZSwcTree_removeBranch(self, tn)

    def shollAnalysis(self, rStart, rEnd, rStep, center):
        return _neutube.ZSwcTree_shollAnalysis(self, rStart, rEnd, rStep, center)

    def firstRegularRoot(self):
        return _neutube.ZSwcTree_firstRegularRoot(self)

    def firstLeaf(self):
        return _neutube.ZSwcTree_firstLeaf(self)

    def getTerminalArray(self):
        return _neutube.ZSwcTree_getTerminalArray(self)

    def extractBranch(self, *args):
        return _neutube.ZSwcTree_extractBranch(self, *args)

    def extractLongestBranch(self):
        return _neutube.ZSwcTree_extractLongestBranch(self)

    def extractFurthestBranch(self):
        return _neutube.ZSwcTree_extractFurthestBranch(self)

    def getLongestPath(self):
        return _neutube.ZSwcTree_getLongestPath(self)

    def extractLeaf(self, start):
        return _neutube.ZSwcTree_extractLeaf(self, start)

    def queryNode(self, *args):
        return _neutube.ZSwcTree_queryNode(self, *args)

    def somaCenter(self):
        return _neutube.ZSwcTree_somaCenter(self)

    def computeAllContinuationAngle(self, rotating=False):
        return _neutube.ZSwcTree_computeAllContinuationAngle(self, rotating)

    def computeAllBranchingAngle(self):
        return _neutube.ZSwcTree_computeAllBranchingAngle(self)

    def merge(self, *args):
        return _neutube.ZSwcTree_merge(self, *args)

    def setLabel(self, v):
        return _neutube.ZSwcTree_setLabel(self, v)

    def setType(self, type):
        return _neutube.ZSwcTree_setType(self, type)

    def translate(self, *args):
        return _neutube.ZSwcTree_translate(self, *args)

    def scale(self, sx, sy, sz):
        return _neutube.ZSwcTree_scale(self, sx, sy, sz)

    def rotate(self, theta, psi, center, inverse=False):
        return _neutube.ZSwcTree_rotate(self, theta, psi, center, inverse)

    def computeCentroid(self):
        return _neutube.ZSwcTree_computeCentroid(self)

    def resample(self, step):
        return _neutube.ZSwcTree_resample(self, step)

    def removeRandomBranch(self):
        return _neutube.ZSwcTree_removeRandomBranch(self)

    def labelSubtree(self, tn, label):
        return _neutube.ZSwcTree_labelSubtree(self, tn, label)

    def addLabelSubtree(self, tn, label):
        return _neutube.ZSwcTree_addLabelSubtree(self, tn, label)

    def labelTrunkLevel(self, trunkAnalyzer):
        return _neutube.ZSwcTree_labelTrunkLevel(self, trunkAnalyzer)

    def markSoma(self, radiusThre=0, somaType=1, otherType=0):
        return _neutube.ZSwcTree_markSoma(self, radiusThre, somaType, otherType)

    def regularDepth(self):
        return _neutube.ZSwcTree_regularDepth(self)

    def mainTrunk(self, trunkAnalyzer):
        return _neutube.ZSwcTree_mainTrunk(self, trunkAnalyzer)

    def subTrunk(self, *args):
        return _neutube.ZSwcTree_subTrunk(self, *args)

    def getBranchArray(self):
        return _neutube.ZSwcTree_getBranchArray(self)

    def setTypeByLabel(self):
        return _neutube.ZSwcTree_setTypeByLabel(self)

    def moveToSurface(self, *args):
        return _neutube.ZSwcTree_moveToSurface(self, *args)

    def deactivateIterator(self):
        return _neutube.ZSwcTree_deactivateIterator(self)

    def activateIterator(self):
        return _neutube.ZSwcTree_activateIterator(self)

    def forceVirtualRoot(self):
        return _neutube.ZSwcTree_forceVirtualRoot(self)

    def setBranchSizeWeight(self):
        return _neutube.ZSwcTree_setBranchSizeWeight(self)

    def length(self, *args):
        return _neutube.ZSwcTree_length(self, *args)

    def computeBackTraceLength(self):
        return _neutube.ZSwcTree_computeBackTraceLength(self)

    def typeSet(self):
        return _neutube.ZSwcTree_typeSet(self)

    def hasGoodSourceName(self):
        return _neutube.ZSwcTree_hasGoodSourceName(self)

    def toSwcTreeNodeArray(self, includingVirtual=True):
        return _neutube.ZSwcTree_toSwcTreeNodeArray(self, includingVirtual)
    DEPTH_FIRST_ITERATOR = _neutube.ZSwcTree_DEPTH_FIRST_ITERATOR
    BREADTH_FIRST_ITERATOR = _neutube.ZSwcTree_BREADTH_FIRST_ITERATOR
    LEAF_ITERATOR = _neutube.ZSwcTree_LEAF_ITERATOR
    TERMINAL_ITERATOR = _neutube.ZSwcTree_TERMINAL_ITERATOR
    BRANCH_POINT_ITERATOR = _neutube.ZSwcTree_BRANCH_POINT_ITERATOR
    Z_SORT_ITERATOR = _neutube.ZSwcTree_Z_SORT_ITERATOR
    ID_SORT_ITERATOR = _neutube.ZSwcTree_ID_SORT_ITERATOR

    def getSwcTreeNodeArray(self, *args):
        return _neutube.ZSwcTree_getSwcTreeNodeArray(self, *args)

    def labelStack(self, stack):
        return _neutube.ZSwcTree_labelStack(self, stack)

    def getMaxSegmentLenth(self):
        return _neutube.ZSwcTree_getMaxSegmentLenth(self)

    def isLinear(self):
        return _neutube.ZSwcTree_isLinear(self)
    COLOR_NORMAL = _neutube.ZSwcTree_COLOR_NORMAL
    COLOR_ROI_CURVE = _neutube.ZSwcTree_COLOR_ROI_CURVE

    def setColorScheme(self, scheme):
        return _neutube.ZSwcTree_setColorScheme(self, scheme)

    def initHostState(self, *args):
        return _neutube.ZSwcTree_initHostState(self, *args)

    def setHostState(self, tn):
        return _neutube.ZSwcTree_setHostState(self, tn)

    def getStructrualMode(self):
        return _neutube.ZSwcTree_getStructrualMode(self)

    def setStructrualMode(self, mode):
        return _neutube.ZSwcTree_setStructrualMode(self, mode)

    def toClosedCurve(self):
        return _neutube.ZSwcTree_toClosedCurve(self)

    def updateHostState(self):
        return _neutube.ZSwcTree_updateHostState(self)

    @staticmethod
    def loadTreeArray(dirPath):
        return _neutube.ZSwcTree_loadTreeArray(dirPath)

    @staticmethod
    def makeArrow(startPos, startSize, startType, endPos, endSize, endType, addBreak=True):
        return _neutube.ZSwcTree_makeArrow(startPos, startSize, startType, endPos, endSize, endType, addBreak)

    @staticmethod
    def generateRandomSwcTree(n, branchingProb, contAngleMu, contAngleSigma, branchAngleMu, branchAngleSigma):
        return _neutube.ZSwcTree_generateRandomSwcTree(n, branchingProb, contAngleMu, contAngleSigma, branchAngleMu, branchAngleSigma)

    @staticmethod
    def getHostState(tn, state):
        return _neutube.ZSwcTree_getHostState(tn, state)

    @staticmethod
    def GetDefaultTarget():
        return _neutube.ZSwcTree_GetDefaultTarget()

# Register ZSwcTree in _neutube:
_neutube.ZSwcTree_swigregister(ZSwcTree)

def swap(first, second):
    return _neutube.swap(first, second)

def ZSwcTree_GetType():
    return _neutube.ZSwcTree_GetType()

def ZSwcTree_CreateCuboidSwc(box, radius=1.0):
    return _neutube.ZSwcTree_CreateCuboidSwc(box, radius)

def ZSwcTree_loadTreeArray(dirPath):
    return _neutube.ZSwcTree_loadTreeArray(dirPath)

def ZSwcTree_makeArrow(startPos, startSize, startType, endPos, endSize, endType, addBreak=True):
    return _neutube.ZSwcTree_makeArrow(startPos, startSize, startType, endPos, endSize, endType, addBreak)

def ZSwcTree_generateRandomSwcTree(n, branchingProb, contAngleMu, contAngleSigma, branchAngleMu, branchAngleSigma):
    return _neutube.ZSwcTree_generateRandomSwcTree(n, branchingProb, contAngleMu, contAngleSigma, branchAngleMu, branchAngleSigma)

def ZSwcTree_getHostState(tn, state):
    return _neutube.ZSwcTree_getHostState(tn, state)

def ZSwcTree_GetDefaultTarget():
    return _neutube.ZSwcTree_GetDefaultTarget()


def EncodeSwcTree(tree):
    return _neutube.EncodeSwcTree(tree)

def DecodeSwcTree(data):
    return _neutube.DecodeSwcTree(data)

def CreateSwcTree():
    return _neutube.CreateSwcTree()

def DeleteSwcTree(tree):
    return _neutube.DeleteSwcTree(tree)
class ZStackSkeletonizer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _neutube.ZStackSkeletonizer_swiginit(self, _neutube.new_ZStackSkeletonizer())

    def configure(self, *args):
        return _neutube.ZStackSkeletonizer_configure(self, *args)

    def setLengthThreshold(self, threshold):
        return _neutube.ZStackSkeletonizer_setLengthThreshold(self, threshold)

    def setDistanceThreshold(self, threshold):
        return _neutube.ZStackSkeletonizer_setDistanceThreshold(self, threshold)

    def setRebase(self, rebase):
        return _neutube.ZStackSkeletonizer_setRebase(self, rebase)

    def setInterpolating(self, inter):
        return _neutube.ZStackSkeletonizer_setInterpolating(self, inter)

    def setRemovingBorder(self, r):
        return _neutube.ZStackSkeletonizer_setRemovingBorder(self, r)

    def setFillingHole(self, f):
        return _neutube.ZStackSkeletonizer_setFillingHole(self, f)

    def setMinObjSize(self, s):
        return _neutube.ZStackSkeletonizer_setMinObjSize(self, s)

    def setKeepingSingleObject(self, k):
        return _neutube.ZStackSkeletonizer_setKeepingSingleObject(self, k)

    def setLevel(self, level):
        return _neutube.ZStackSkeletonizer_setLevel(self, level)

    def setLevelOp(self, op):
        return _neutube.ZStackSkeletonizer_setLevelOp(self, op)

    def setResolution(self, xyRes, zRes):
        return _neutube.ZStackSkeletonizer_setResolution(self, xyRes, zRes)

    def setDownsampleInterval(self, xintv, yintv, zintv):
        return _neutube.ZStackSkeletonizer_setDownsampleInterval(self, xintv, yintv, zintv)

    def getDownsampleInterval(self, xintv, yintv, zintv):
        return _neutube.ZStackSkeletonizer_getDownsampleInterval(self, xintv, yintv, zintv)

    def makeSkeleton(self, *args):
        return _neutube.ZStackSkeletonizer_makeSkeleton(self, *args)

    def reconnect(self, tree):
        return _neutube.ZStackSkeletonizer_reconnect(self, tree)

    def setConnectingBranch(self, conn):
        return _neutube.ZStackSkeletonizer_setConnectingBranch(self, conn)

    def _print(self):
        return _neutube.ZStackSkeletonizer__print(self)

    def useOriginalSignal(self, state):
        return _neutube.ZStackSkeletonizer_useOriginalSignal(self, state)
    __swig_destroy__ = _neutube.delete_ZStackSkeletonizer

# Register ZStackSkeletonizer in _neutube:
_neutube.ZStackSkeletonizer_swigregister(ZStackSkeletonizer)

class ZClosedCurve(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _neutube.ZClosedCurve_swiginit(self, _neutube.new_ZClosedCurve())

    def isEmpty(self):
        return _neutube.ZClosedCurve_isEmpty(self)

    def getLandmarkNumber(self):
        return _neutube.ZClosedCurve_getLandmarkNumber(self)

    def getLandmark(self, index):
        return _neutube.ZClosedCurve_getLandmark(self, index)

    def getLength(self):
        return _neutube.ZClosedCurve_getLength(self)

    def resampleF(self, n):
        return _neutube.ZClosedCurve_resampleF(self, n)

    def findMatchShift(self, target):
        return _neutube.ZClosedCurve_findMatchShift(self, target)

    def getSegmentNumber(self):
        return _neutube.ZClosedCurve_getSegmentNumber(self)

    def getSegment(self, index):
        return _neutube.ZClosedCurve_getSegment(self, index)

    def append(self, *args):
        return _neutube.ZClosedCurve_append(self, *args)

    def interpolate(self, *args):
        return _neutube.ZClosedCurve_interpolate(self, *args)

    def reverse(self):
        return _neutube.ZClosedCurve_reverse(self)

    def getMinXIndex(self):
        return _neutube.ZClosedCurve_getMinXIndex(self)

    def getMinYIndex(self):
        return _neutube.ZClosedCurve_getMinYIndex(self)

    def _print(self):
        return _neutube.ZClosedCurve__print(self)

    def loadJsonObject(self, obj):
        return _neutube.ZClosedCurve_loadJsonObject(self, obj)

    def toJsonObject(self):
        return _neutube.ZClosedCurve_toJsonObject(self)

    def clear(self):
        return _neutube.ZClosedCurve_clear(self)

    def computeCenter(self):
        return _neutube.ZClosedCurve_computeCenter(self)

    def computeDirection(self):
        return _neutube.ZClosedCurve_computeDirection(self)

    def getBoundBox(self):
        return _neutube.ZClosedCurve_getBoundBox(self)

    def scale(self, sx, sy, sz):
        return _neutube.ZClosedCurve_scale(self, sx, sy, sz)

    def translate(self, dx, dy):
        return _neutube.ZClosedCurve_translate(self, dx, dy)

    def clone(self):
        return _neutube.ZClosedCurve_clone(self)
    __swig_destroy__ = _neutube.delete_ZClosedCurve

# Register ZClosedCurve in _neutube:
_neutube.ZClosedCurve_swigregister(ZClosedCurve)

class ZObject3dScan(ZStackObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _neutube.delete_ZObject3dScan

    def __init__(self, *args):
        _neutube.ZObject3dScan_swiginit(self, _neutube.new_ZObject3dScan(*args))
    COMPONENT_STRIPE_INDEX_MAP = _neutube.ZObject3dScan_COMPONENT_STRIPE_INDEX_MAP
    COMPONENT_INDEX_SEGMENT_MAP = _neutube.ZObject3dScan_COMPONENT_INDEX_SEGMENT_MAP
    COMPONENT_ACCUMULATED_STRIPE_NUMBER = _neutube.ZObject3dScan_COMPONENT_ACCUMULATED_STRIPE_NUMBER
    COMPONENT_SLICEWISE_VOXEL_NUMBER = _neutube.ZObject3dScan_COMPONENT_SLICEWISE_VOXEL_NUMBER
    COMPONENT_Z_PROJECTION = _neutube.ZObject3dScan_COMPONENT_Z_PROJECTION
    COMPONENT_ALL = _neutube.ZObject3dScan_COMPONENT_ALL
    ACTION_NONE = _neutube.ZObject3dScan_ACTION_NONE
    ACTION_CANONIZE = _neutube.ZObject3dScan_ACTION_CANONIZE
    ACTION_SORT_YZ = _neutube.ZObject3dScan_ACTION_SORT_YZ

    def isDeprecated(self, comp):
        return _neutube.ZObject3dScan_isDeprecated(self, comp)

    def deprecate(self, comp):
        return _neutube.ZObject3dScan_deprecate(self, comp)

    def deprecateDependent(self, comp):
        return _neutube.ZObject3dScan_deprecateDependent(self, comp)

    def clear(self):
        return _neutube.ZObject3dScan_clear(self)

    def toObject3d(self):
        return _neutube.ZObject3dScan_toObject3d(self)

    def isEmpty(self):
        return _neutube.ZObject3dScan_isEmpty(self)

    def getStripeNumber(self):
        return _neutube.ZObject3dScan_getStripeNumber(self)

    def getVoxelNumber(self, *args):
        return _neutube.ZObject3dScan_getVoxelNumber(self, *args)

    def getSlicewiseVoxelNumber(self, *args):
        return _neutube.ZObject3dScan_getSlicewiseVoxelNumber(self, *args)

    def getStripe(self, *args):
        return _neutube.ZObject3dScan_getStripe(self, *args)

    def addStripeFast(self, *args):
        return _neutube.ZObject3dScan_addStripeFast(self, *args)

    def addSegmentFast(self, x1, x2):
        return _neutube.ZObject3dScan_addSegmentFast(self, x1, x2)

    def addSegment(self, *args):
        return _neutube.ZObject3dScan_addSegment(self, *args)

    def addStripe(self, *args):
        return _neutube.ZObject3dScan_addStripe(self, *args)

    def loadStack(self, *args):
        return _neutube.ZObject3dScan_loadStack(self, *args)

    def _print(self):
        return _neutube.ZObject3dScan__print(self)

    def save(self, *args):
        return _neutube.ZObject3dScan_save(self, *args)

    def hit(self, *args):
        return _neutube.ZObject3dScan_hit(self, *args)

    def copyDataFrom(self, obj):
        return _neutube.ZObject3dScan_copyDataFrom(self, obj)

    def importDvidObject(self, filePath):
        return _neutube.ZObject3dScan_importDvidObject(self, filePath)

    def exportDvidObject(self, filePath):
        return _neutube.ZObject3dScan_exportDvidObject(self, filePath)

    def importDvidObjectBuffer(self, *args):
        return _neutube.ZObject3dScan_importDvidObjectBuffer(self, *args)

    def importDvidRoi(self, *args):
        return _neutube.ZObject3dScan_importDvidRoi(self, *args)

    def labelStack(self, stack, startLabel, offset=None):
        return _neutube.ZObject3dScan_labelStack(self, stack, startLabel, offset)

    def drawStack(self, *args):
        return _neutube.ZObject3dScan_drawStack(self, *args)

    def maskStack(self, stack):
        return _neutube.ZObject3dScan_maskStack(self, stack)

    def countForegroundOverlap(self, stack, offset=None):
        return _neutube.ZObject3dScan_countForegroundOverlap(self, stack, offset)

    def sort(self):
        return _neutube.ZObject3dScan_sort(self)

    def canonize(self):
        return _neutube.ZObject3dScan_canonize(self)

    def unify(self, obj):
        return _neutube.ZObject3dScan_unify(self, obj)

    def concat(self, obj):
        return _neutube.ZObject3dScan_concat(self, obj)

    def subtract(self, obj):
        return _neutube.ZObject3dScan_subtract(self, obj)

    def subtractSliently(self, obj):
        return _neutube.ZObject3dScan_subtractSliently(self, obj)

    def intersect(self, obj):
        return _neutube.ZObject3dScan_intersect(self, obj)

    def subobject(self, box, result=None):
        return _neutube.ZObject3dScan_subobject(self, box, result)

    def downsample(self, xintv, yintv, zintv):
        return _neutube.ZObject3dScan_downsample(self, xintv, yintv, zintv)

    def downsampleMax(self, xintv, yintv, zintv):
        return _neutube.ZObject3dScan_downsampleMax(self, xintv, yintv, zintv)

    def upSample(self, xIntv, yIntv, zIntv):
        return _neutube.ZObject3dScan_upSample(self, xIntv, yIntv, zIntv)

    def toStack(self, offset=None, v=1):
        return _neutube.ZObject3dScan_toStack(self, offset, v)

    def toStackWithMargin(self, offset, v, margin):
        return _neutube.ZObject3dScan_toStackWithMargin(self, offset, v, margin)

    def toStackObject(self, v=1):
        return _neutube.ZObject3dScan_toStackObject(self, v)

    def toStackObjectWithMargin(self, v, margin):
        return _neutube.ZObject3dScan_toStackObjectWithMargin(self, v, margin)

    def toVirtualStack(self):
        return _neutube.ZObject3dScan_toVirtualStack(self)

    def getBoundBox(self, *args):
        return _neutube.ZObject3dScan_getBoundBox(self, *args)

    @staticmethod
    def extractAllObject(stack, yStep=1):
        return _neutube.ZObject3dScan_extractAllObject(stack, yStep)

    def buildConnectionGraph(self):
        return _neutube.ZObject3dScan_buildConnectionGraph(self)

    def getStripeNumberAccumulation(self):
        return _neutube.ZObject3dScan_getStripeNumberAccumulation(self)

    def getStripeMap(self):
        return _neutube.ZObject3dScan_getStripeMap(self)

    def getConnectedObjectSize(self):
        return _neutube.ZObject3dScan_getConnectedObjectSize(self)

    def getConnectedComponent(self, ppAction):
        return _neutube.ZObject3dScan_getConnectedComponent(self, ppAction)

    def isCanonized(self):
        return _neutube.ZObject3dScan_isCanonized(self)

    def setCanonized(self, canonized):
        return _neutube.ZObject3dScan_setCanonized(self, canonized)

    def getIndexSegmentMap(self):
        return _neutube.ZObject3dScan_getIndexSegmentMap(self)

    def getSegment(self, index, z, y, x1, x2):
        return _neutube.ZObject3dScan_getSegment(self, index, z, y, x1, x2)

    def getSegmentNumber(self):
        return _neutube.ZObject3dScan_getSegmentNumber(self)

    def translate(self, *args):
        return _neutube.ZObject3dScan_translate(self, *args)

    def isCanonizedActually(self):
        return _neutube.ZObject3dScan_isCanonizedActually(self)

    def duplicateSlice(self, depth):
        return _neutube.ZObject3dScan_duplicateSlice(self, depth)

    def getMedianSlice(self):
        return _neutube.ZObject3dScan_getMedianSlice(self)

    def getSlice(self, *args):
        return _neutube.ZObject3dScan_getSlice(self, *args)

    def interpolateSlice(self, z):
        return _neutube.ZObject3dScan_interpolateSlice(self, z)

    def getFirstSlice(self):
        return _neutube.ZObject3dScan_getFirstSlice(self)

    def display(self, painter, slice, option, sliceAxis):
        return _neutube.ZObject3dScan_display(self, painter, slice, option, sliceAxis)

    def className(self):
        return _neutube.ZObject3dScan_className(self)

    def dilate(self):
        return _neutube.ZObject3dScan_dilate(self)

    def dilatePlane(self):
        return _neutube.ZObject3dScan_dilatePlane(self)

    def getCentroid(self):
        return _neutube.ZObject3dScan_getCentroid(self)

    def getMarker(self):
        return _neutube.ZObject3dScan_getMarker(self)

    def getRadialHistogram(self, z):
        return _neutube.ZObject3dScan_getRadialHistogram(self, z)

    def makeZProjection(self, *args):
        return _neutube.ZObject3dScan_makeZProjection(self, *args)

    def makeYProjection(self):
        return _neutube.ZObject3dScan_makeYProjection(self)

    def getZProjection(self):
        return _neutube.ZObject3dScan_getZProjection(self)

    def contains(self, *args):
        return _neutube.ZObject3dScan_contains(self, *args)

    def getMinZ(self):
        return _neutube.ZObject3dScan_getMinZ(self)

    def getMaxZ(self):
        return _neutube.ZObject3dScan_getMaxZ(self)

    def getMinY(self):
        return _neutube.ZObject3dScan_getMinY(self)

    def getMaxY(self):
        return _neutube.ZObject3dScan_getMaxY(self)

    def equalsLiterally(self, obj):
        return _neutube.ZObject3dScan_equalsLiterally(self, obj)

    def getSurfaceArea(self):
        return _neutube.ZObject3dScan_getSurfaceArea(self)

    def getComplementObject(self):
        return _neutube.ZObject3dScan_getComplementObject(self)

    def getSurfaceObject(self):
        return _neutube.ZObject3dScan_getSurfaceObject(self)

    def findHoleObject(self):
        return _neutube.ZObject3dScan_findHoleObject(self)

    def findHoleObjectArray(self):
        return _neutube.ZObject3dScan_findHoleObjectArray(self)

    def fillHole(self):
        return _neutube.ZObject3dScan_fillHole(self)

    def switchYZ(self):
        return _neutube.ZObject3dScan_switchYZ(self)

    def getSpread(self, z):
        return _neutube.ZObject3dScan_getSpread(self, z)

    def getPlaneCov(self):
        return _neutube.ZObject3dScan_getPlaneCov(self)

    def processEvent(self, event):
        return _neutube.ZObject3dScan_processEvent(self, event)

    def blockEvent(self, blocking):
        return _neutube.ZObject3dScan_blockEvent(self, blocking)

    def toIntArray(self):
        return _neutube.ZObject3dScan_toIntArray(self)

    def load(self, *args):
        return _neutube.ZObject3dScan_load(self, *args)

    def importHdf5(self, filePath, key):
        return _neutube.ZObject3dScan_importHdf5(self, filePath, key)

    def hasOverlap(self, obj):
        return _neutube.ZObject3dScan_hasOverlap(self, obj)

    def isAdjacentTo(self, obj):
        return _neutube.ZObject3dScan_isAdjacentTo(self, obj)

    def getLabel(self):
        return _neutube.ZObject3dScan_getLabel(self)

    def setLabel(self, label):
        return _neutube.ZObject3dScan_setLabel(self, label)

    def getStripeArray(self):
        return _neutube.ZObject3dScan_getStripeArray(self)

# Register ZObject3dScan in _neutube:
_neutube.ZObject3dScan_swigregister(ZObject3dScan)

def ZObject3dScan_extractAllObject(stack, yStep=1):
    return _neutube.ZObject3dScan_extractAllObject(stack, yStep)


def CreateObject3dScan():
    return _neutube.CreateObject3dScan()

def DeleteObject3dScan(obj):
    return _neutube.DeleteObject3dScan(obj)

def darray_max(d1, length, idx):
    return _neutube.darray_max(d1, length, idx)

def darray_min(d1, length, idx):
    return _neutube.darray_min(d1, length, idx)

def darray_max_m(d1, length, mask, idx):
    return _neutube.darray_max_m(d1, length, mask, idx)

def darray_min_m(d1, length, mask, idx):
    return _neutube.darray_min_m(d1, length, mask, idx)

def darray_max_l(d1, length, idx):
    return _neutube.darray_max_l(d1, length, idx)

def darray_min_l(d1, length, idx):
    return _neutube.darray_min_l(d1, length, idx)

def darray_max_ml(d1, length, mask, idx):
    return _neutube.darray_max_ml(d1, length, mask, idx)

def darray_min_ml(d1, length, mask, idx):
    return _neutube.darray_min_ml(d1, length, mask, idx)

def darray_max_n(d1, length, idx):
    return _neutube.darray_max_n(d1, length, idx)
class ZStackFile(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _neutube.ZStackFile_swiginit(self, _neutube.new_ZStackFile(*args))
    UNIDENTIFIED = _neutube.ZStackFile_UNIDENTIFIED
    SINGLE_FILE = _neutube.ZStackFile_SINGLE_FILE
    FILE_BUNDLE = _neutube.ZStackFile_FILE_BUNDLE
    IMAGE_SERIES = _neutube.ZStackFile_IMAGE_SERIES
    FILE_LIST = _neutube.ZStackFile_FILE_LIST
    SOBJ_LIST = _neutube.ZStackFile_SOBJ_LIST
    HDF5_DATASET = _neutube.ZStackFile_HDF5_DATASET

    def readStack(self, data=None, initColor=True):
        return _neutube.ZStackFile_readStack(self, data, initColor)

    def toFileBundleS(self):
        return _neutube.ZStackFile_toFileBundleS(self)

    def toFileList(self):
        return _neutube.ZStackFile_toFileList(self)

    def _import(self, *args):
        return _neutube.ZStackFile__import(self, *args)

    def importImageSeries(self, filePath):
        return _neutube.ZStackFile_importImageSeries(self, filePath)

    def importSobjList(self, fileList):
        return _neutube.ZStackFile_importSobjList(self, fileList)

    def loadJsonObject(self, obj, source):
        return _neutube.ZStackFile_loadJsonObject(self, obj, source)

    def loadStackDocument(self, doc):
        return _neutube.ZStackFile_loadStackDocument(self, doc)

    def importJsonFile(self, filePath):
        return _neutube.ZStackFile_importJsonFile(self, filePath)

    def importXmlFile(self, filePath):
        return _neutube.ZStackFile_importXmlFile(self, filePath)

    def retrieveAttribute(self, kind, width, height, depth):
        return _neutube.ZStackFile_retrieveAttribute(self, kind, width, height, depth)

    def firstUrl(self):
        return _neutube.ZStackFile_firstUrl(self)

    def prefix(self):
        return _neutube.ZStackFile_prefix(self)

    def suffix(self):
        return _neutube.ZStackFile_suffix(self)

    def numWidth(self):
        return _neutube.ZStackFile_numWidth(self)

    def firstNum(self):
        return _neutube.ZStackFile_firstNum(self)

    def channel(self):
        return _neutube.ZStackFile_channel(self)

    def setChannel(self, channel):
        return _neutube.ZStackFile_setChannel(self, channel)

    def countImageSeries(self):
        return _neutube.ZStackFile_countImageSeries(self)

    def _print(self):
        return _neutube.ZStackFile__print(self)

    @staticmethod
    def isStackTag(tag):
        return _neutube.ZStackFile_isStackTag(tag)

    @staticmethod
    def isUrlTag(tag):
        return _neutube.ZStackFile_isUrlTag(tag)

    @staticmethod
    def isPrefixTag(tag):
        return _neutube.ZStackFile_isPrefixTag(tag)

    @staticmethod
    def isSuffixTag(tag):
        return _neutube.ZStackFile_isSuffixTag(tag)

    @staticmethod
    def isNumWidthTag(tag):
        return _neutube.ZStackFile_isNumWidthTag(tag)

    @staticmethod
    def isFirstNumTag(tag):
        return _neutube.ZStackFile_isFirstNumTag(tag)

    @staticmethod
    def isTypeTag(tag):
        return _neutube.ZStackFile_isTypeTag(tag)

    @staticmethod
    def isLastNumTag(tag):
        return _neutube.ZStackFile_isLastNumTag(tag)

    @staticmethod
    def isChannelTag(tag):
        return _neutube.ZStackFile_isChannelTag(tag)

    @staticmethod
    def isDimFlipTag(tag):
        return _neutube.ZStackFile_isDimFlipTag(tag)

    def fileBundlePath(self, n):
        return _neutube.ZStackFile_fileBundlePath(self, n)

    def setType(self, str):
        return _neutube.ZStackFile_setType(self, str)

    def type(self):
        return _neutube.ZStackFile_type(self)

    def appendUrl(self, path):
        return _neutube.ZStackFile_appendUrl(self, path)

    def clear(self):
        return _neutube.ZStackFile_clear(self)
    __swig_destroy__ = _neutube.delete_ZStackFile

# Register ZStackFile in _neutube:
_neutube.ZStackFile_swigregister(ZStackFile)

def ZStackFile_isStackTag(tag):
    return _neutube.ZStackFile_isStackTag(tag)

def ZStackFile_isUrlTag(tag):
    return _neutube.ZStackFile_isUrlTag(tag)

def ZStackFile_isPrefixTag(tag):
    return _neutube.ZStackFile_isPrefixTag(tag)

def ZStackFile_isSuffixTag(tag):
    return _neutube.ZStackFile_isSuffixTag(tag)

def ZStackFile_isNumWidthTag(tag):
    return _neutube.ZStackFile_isNumWidthTag(tag)

def ZStackFile_isFirstNumTag(tag):
    return _neutube.ZStackFile_isFirstNumTag(tag)

def ZStackFile_isTypeTag(tag):
    return _neutube.ZStackFile_isTypeTag(tag)

def ZStackFile_isLastNumTag(tag):
    return _neutube.ZStackFile_isLastNumTag(tag)

def ZStackFile_isChannelTag(tag):
    return _neutube.ZStackFile_isChannelTag(tag)

def ZStackFile_isDimFlipTag(tag):
    return _neutube.ZStackFile_isDimFlipTag(tag)

class ZPointArray(Point_Array):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _neutube.ZPointArray_swiginit(self, _neutube.new_ZPointArray())

    def translate(self, pt):
        return _neutube.ZPointArray_translate(self, pt)

    def scale(self, sx, sy, sz):
        return _neutube.ZPointArray_scale(self, sx, sy, sz)

    def exportSwcFile(self, filePath, radius):
        return _neutube.ZPointArray_exportSwcFile(self, filePath, radius)

    def exportTxtFile(self, filePath):
        return _neutube.ZPointArray_exportTxtFile(self, filePath)

    def _print(self):
        return _neutube.ZPointArray__print(self)

    def importTxtFile(self, filePath):
        return _neutube.ZPointArray_importTxtFile(self, filePath)

    def importPcdFile(self, filePath):
        return _neutube.ZPointArray_importPcdFile(self, filePath)

    def append(self, *args):
        return _neutube.ZPointArray_append(self, *args)

    def toJsonString(self):
        return _neutube.ZPointArray_toJsonString(self)

    def computeCenter(self):
        return _neutube.ZPointArray_computeCenter(self)

    def getBoundBox(self):
        return _neutube.ZPointArray_getBoundBox(self)

    def computePlaneCov(self):
        return _neutube.ZPointArray_computePlaneCov(self)

    def isEmpty(self):
        return _neutube.ZPointArray_isEmpty(self)

    def computeDistanceGraph(self, *args):
        return _neutube.ZPointArray_computeDistanceGraph(self, *args)
    __swig_destroy__ = _neutube.delete_ZPointArray

# Register ZPointArray in _neutube:
_neutube.ZPointArray_swigregister(ZPointArray)


def CreateZPointArray():
    return _neutube.CreateZPointArray()

def DeleteZPointArray(obj):
    return _neutube.DeleteZPointArray(obj)
class ZFlyEmNeuron(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _neutube.delete_ZFlyEmNeuron

    def __init__(self, *args):
        _neutube.ZFlyEmNeuron_swiginit(self, _neutube.new_ZFlyEmNeuron(*args))
    MODEL = _neutube.ZFlyEmNeuron_MODEL
    UNSCALED_MODEL = _neutube.ZFlyEmNeuron_UNSCALED_MODEL
    BODY = _neutube.ZFlyEmNeuron_BODY
    BUDDY_MODEL = _neutube.ZFlyEmNeuron_BUDDY_MODEL
    ALL_COMPONENT = _neutube.ZFlyEmNeuron_ALL_COMPONENT

    def isDeprecated(self, comp):
        return _neutube.ZFlyEmNeuron_isDeprecated(self, comp)

    def deprecate(self, comp):
        return _neutube.ZFlyEmNeuron_deprecate(self, comp)

    def deprecateDependent(self, comp):
        return _neutube.ZFlyEmNeuron_deprecateDependent(self, comp)

    def loadJsonObject(self, obj, source):
        return _neutube.ZFlyEmNeuron_loadJsonObject(self, obj, source)

    def getAnnotationJson(self):
        return _neutube.ZFlyEmNeuron_getAnnotationJson(self)

    def makeJsonObject(self, *args):
        return _neutube.ZFlyEmNeuron_makeJsonObject(self, *args)

    def setName(self, name):
        return _neutube.ZFlyEmNeuron_setName(self, name)

    def getName(self):
        return _neutube.ZFlyEmNeuron_getName(self)

    def setType(self, c):
        return _neutube.ZFlyEmNeuron_setType(self, c)

    def getType(self):
        return _neutube.ZFlyEmNeuron_getType(self)

    def getClass(self):
        return _neutube.ZFlyEmNeuron_getClass(self)

    def getSuperclass(self):
        return _neutube.ZFlyEmNeuron_getSuperclass(self)

    def hasType(self):
        return _neutube.ZFlyEmNeuron_hasType(self)

    def setId(self, *args):
        return _neutube.ZFlyEmNeuron_setId(self, *args)

    def getId(self):
        return _neutube.ZFlyEmNeuron_getId(self)

    def getSourceId(self):
        return _neutube.ZFlyEmNeuron_getSourceId(self)

    def setSourceId(self, id):
        return _neutube.ZFlyEmNeuron_setSourceId(self, id)

    def setPath(self, target):
        return _neutube.ZFlyEmNeuron_setPath(self, target)

    def setModelPath(self, path):
        return _neutube.ZFlyEmNeuron_setModelPath(self, path)

    def getModelPath(self):
        return _neutube.ZFlyEmNeuron_getModelPath(self)

    def getVolumePath(self):
        return _neutube.ZFlyEmNeuron_getVolumePath(self)

    def getThumbnailPath(self):
        return _neutube.ZFlyEmNeuron_getThumbnailPath(self)

    def updateDvidModel(self, forceUpdate):
        return _neutube.ZFlyEmNeuron_updateDvidModel(self, forceUpdate)

    def getModel(self, *args):
        return _neutube.ZFlyEmNeuron_getModel(self, *args)

    def getUnscaledModel(self, *args):
        return _neutube.ZFlyEmNeuron_getUnscaledModel(self, *args)

    def setModel(self, tree):
        return _neutube.ZFlyEmNeuron_setModel(self, tree)

    def setUnscaledModel(self, tree):
        return _neutube.ZFlyEmNeuron_setUnscaledModel(self, tree)

    def getResampleBuddyModel(self, *args):
        return _neutube.ZFlyEmNeuron_getResampleBuddyModel(self, *args)

    def getAxis(self):
        return _neutube.ZFlyEmNeuron_getAxis(self)

    def setResolution(self, res):
        return _neutube.ZFlyEmNeuron_setResolution(self, res)

    def _print(self, *args):
        return _neutube.ZFlyEmNeuron__print(self, *args)

    def printJson(self, stream, indent):
        return _neutube.ZFlyEmNeuron_printJson(self, stream, indent)

    def hasSimilarName(self, name):
        return _neutube.ZFlyEmNeuron_hasSimilarName(self, name)

    def getTopMatch(self):
        return _neutube.ZFlyEmNeuron_getTopMatch(self)

    def setSynapseScale(self, scale):
        return _neutube.ZFlyEmNeuron_setSynapseScale(self, scale)

    def setSynapseAnnotation(self, annotation):
        return _neutube.ZFlyEmNeuron_setSynapseAnnotation(self, annotation)

    def getTBarNumber(self):
        return _neutube.ZFlyEmNeuron_getTBarNumber(self)

    def getPsdNumber(self):
        return _neutube.ZFlyEmNeuron_getPsdNumber(self)

    def getInputNeuronNumber(self):
        return _neutube.ZFlyEmNeuron_getInputNeuronNumber(self)

    def getOutputNeuronNumber(self):
        return _neutube.ZFlyEmNeuron_getOutputNeuronNumber(self)

    def getStrongestInput(self):
        return _neutube.ZFlyEmNeuron_getStrongestInput(self)

    def getStrongestOutput(self):
        return _neutube.ZFlyEmNeuron_getStrongestOutput(self)

    def appendInputNeuron(self, neuron, weight):
        return _neutube.ZFlyEmNeuron_appendInputNeuron(self, neuron, weight)

    def appendOutputNeuron(self, neuron, weight):
        return _neutube.ZFlyEmNeuron_appendOutputNeuron(self, neuron, weight)

    def clearConnection(self):
        return _neutube.ZFlyEmNeuron_clearConnection(self)

    def getInputNeuron(self, index):
        return _neutube.ZFlyEmNeuron_getInputNeuron(self, index)

    def getOutputNeuron(self, index):
        return _neutube.ZFlyEmNeuron_getOutputNeuron(self, index)

    def toString(self):
        return _neutube.ZFlyEmNeuron_toString(self)

    def getBody(self):
        return _neutube.ZFlyEmNeuron_getBody(self)

    def getRange(self, xyRes, zRes):
        return _neutube.ZFlyEmNeuron_getRange(self, xyRes, zRes)

    def getBodyVolume(self, cacheBody=True):
        return _neutube.ZFlyEmNeuron_getBodyVolume(self, cacheBody)

    def setVolumePath(self, path):
        return _neutube.ZFlyEmNeuron_setVolumePath(self, path)

    def setThumbnailPath(self, path):
        return _neutube.ZFlyEmNeuron_setThumbnailPath(self, path)

    def getSwcResolution(self):
        return _neutube.ZFlyEmNeuron_getSwcResolution(self)

    def importBodyFromHdf5(self, filePath, key):
        return _neutube.ZFlyEmNeuron_importBodyFromHdf5(self, filePath, key)

    def releaseBody(self):
        return _neutube.ZFlyEmNeuron_releaseBody(self)

    def releaseModel(self):
        return _neutube.ZFlyEmNeuron_releaseModel(self)

# Register ZFlyEmNeuron in _neutube:
_neutube.ZFlyEmNeuron_swigregister(ZFlyEmNeuron)
cvar = _neutube.cvar
ZFlyEmNeuron.TopMatchCapacity = _neutube.cvar.ZFlyEmNeuron_TopMatchCapacity


def CreateZFlyEmNeuron(*args):
    return _neutube.CreateZFlyEmNeuron(*args)

def DeleteZFlyEmNeuron(obj):
    return _neutube.DeleteZFlyEmNeuron(obj)
class ZFlyEmQualityAnalyzer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _neutube.ZFlyEmQualityAnalyzer_swiginit(self, _neutube.new_ZFlyEmQualityAnalyzer())

    def isExitingOrphanBody(self, obj):
        return _neutube.ZFlyEmQualityAnalyzer_isExitingOrphanBody(self, obj)

    def isStitchedOrphanBody(self, obj):
        return _neutube.ZFlyEmQualityAnalyzer_isStitchedOrphanBody(self, obj)

    def isOrphanBody(self, obj):
        return _neutube.ZFlyEmQualityAnalyzer_isOrphanBody(self, obj)

    def setSubstackRegion(self, *args):
        return _neutube.ZFlyEmQualityAnalyzer_setSubstackRegion(self, *args)

    @staticmethod
    def labelSwcNodeOutOfRange(neuron, range, label):
        return _neutube.ZFlyEmQualityAnalyzer_labelSwcNodeOutOfRange(neuron, range, label)

    def touchingGlobalBoundary(self, obj):
        return _neutube.ZFlyEmQualityAnalyzer_touchingGlobalBoundary(self, obj)

    def touchingSideBoundary(self, obj):
        return _neutube.ZFlyEmQualityAnalyzer_touchingSideBoundary(self, obj)

    def isInternalFaceOrphan(self, obj):
        return _neutube.ZFlyEmQualityAnalyzer_isInternalFaceOrphan(self, obj)

    def computeHotSpot(self, *args):
        return _neutube.ZFlyEmQualityAnalyzer_computeHotSpot(self, *args)

    def computeHotSpotForSplit(self, neuron):
        return _neutube.ZFlyEmQualityAnalyzer_computeHotSpotForSplit(self, neuron)
    __swig_destroy__ = _neutube.delete_ZFlyEmQualityAnalyzer

# Register ZFlyEmQualityAnalyzer in _neutube:
_neutube.ZFlyEmQualityAnalyzer_swigregister(ZFlyEmQualityAnalyzer)

def ZFlyEmQualityAnalyzer_labelSwcNodeOutOfRange(neuron, range, label):
    return _neutube.ZFlyEmQualityAnalyzer_labelSwcNodeOutOfRange(neuron, range, label)


def CreateZFlyEmQualityAnalyzer():
    return _neutube.CreateZFlyEmQualityAnalyzer()

def DeleteZFlyEmQualityAnalyzer(obj):
    return _neutube.DeleteZFlyEmQualityAnalyzer(obj)
class ZHotSpotArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _neutube.ZHotSpotArray_swiginit(self, _neutube.new_ZHotSpotArray())
    __swig_destroy__ = _neutube.delete_ZHotSpotArray

    def append(self, hotSpot):
        return _neutube.ZHotSpotArray_append(self, hotSpot)

    def concat(self, spotArray):
        return _neutube.ZHotSpotArray_concat(self, spotArray)

    def toString(self):
        return _neutube.ZHotSpotArray_toString(self)

    def _print(self):
        return _neutube.ZHotSpotArray__print(self)

    def toLineCompositer(self):
        return _neutube.ZHotSpotArray_toLineCompositer(self)

    def toJsonString(self):
        return _neutube.ZHotSpotArray_toJsonString(self)

    def exportJsonFile(self, filePath):
        return _neutube.ZHotSpotArray_exportJsonFile(self, filePath)

    def exportRavelerBookmark(self, filePath, resolution, imageSize):
        return _neutube.ZHotSpotArray_exportRavelerBookmark(self, filePath, resolution, imageSize)

    def toPointArray(self):
        return _neutube.ZHotSpotArray_toPointArray(self)

    def toLineSegmentArray(self):
        return _neutube.ZHotSpotArray_toLineSegmentArray(self)

    def sort(self):
        return _neutube.ZHotSpotArray_sort(self)

# Register ZHotSpotArray in _neutube:
_neutube.ZHotSpotArray_swigregister(ZHotSpotArray)


def CreateHotSpotArray():
    return _neutube.CreateHotSpotArray()

def DeleteHotSpotArray(obj):
    return _neutube.DeleteHotSpotArray(obj)
class ZIntCuboid(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _neutube.ZIntCuboid_swiginit(self, _neutube.new_ZIntCuboid(*args))

    def getFirstCorner(self):
        return _neutube.ZIntCuboid_getFirstCorner(self)

    def getLastCorner(self):
        return _neutube.ZIntCuboid_getLastCorner(self)

    def setFirstCorner(self, *args):
        return _neutube.ZIntCuboid_setFirstCorner(self, *args)

    def getCorner(self, index):
        return _neutube.ZIntCuboid_getCorner(self, index)

    def setLastCorner(self, *args):
        return _neutube.ZIntCuboid_setLastCorner(self, *args)

    def reset(self):
        return _neutube.ZIntCuboid_reset(self)

    def set(self, *args):
        return _neutube.ZIntCuboid_set(self, *args)

    def setFirstX(self, x):
        return _neutube.ZIntCuboid_setFirstX(self, x)

    def setLastX(self, x):
        return _neutube.ZIntCuboid_setLastX(self, x)

    def setFirstY(self, y):
        return _neutube.ZIntCuboid_setFirstY(self, y)

    def setLastY(self, y):
        return _neutube.ZIntCuboid_setLastY(self, y)

    def setFirstZ(self, z):
        return _neutube.ZIntCuboid_setFirstZ(self, z)

    def setLastZ(self, z):
        return _neutube.ZIntCuboid_setLastZ(self, z)

    def translateX(self, dx):
        return _neutube.ZIntCuboid_translateX(self, dx)

    def setSize(self, width, height, depth):
        return _neutube.ZIntCuboid_setSize(self, width, height, depth)

    def setWidth(self, width):
        return _neutube.ZIntCuboid_setWidth(self, width)

    def getWidth(self):
        return _neutube.ZIntCuboid_getWidth(self)

    def getHeight(self):
        return _neutube.ZIntCuboid_getHeight(self)

    def getDepth(self):
        return _neutube.ZIntCuboid_getDepth(self)

    def setDepth(self, depth):
        return _neutube.ZIntCuboid_setDepth(self, depth)

    def join(self, cuboid):
        return _neutube.ZIntCuboid_join(self, cuboid)

    def joinX(self, x):
        return _neutube.ZIntCuboid_joinX(self, x)

    def joinY(self, y):
        return _neutube.ZIntCuboid_joinY(self, y)

    def joinZ(self, z):
        return _neutube.ZIntCuboid_joinZ(self, z)

    def expandX(self, dx):
        return _neutube.ZIntCuboid_expandX(self, dx)

    def expandY(self, dy):
        return _neutube.ZIntCuboid_expandY(self, dy)

    def intersect(self, cuboid):
        return _neutube.ZIntCuboid_intersect(self, cuboid)

    def getVolume(self):
        return _neutube.ZIntCuboid_getVolume(self)

    def contains(self, *args):
        return _neutube.ZIntCuboid_contains(self, *args)

    def containYZ(self, y, z):
        return _neutube.ZIntCuboid_containYZ(self, y, z)

    def isEmpty(self):
        return _neutube.ZIntCuboid_isEmpty(self)

    def equals(self, cuboid):
        return _neutube.ZIntCuboid_equals(self, cuboid)

    def hasOverlap(self, box):
        return _neutube.ZIntCuboid_hasOverlap(self, box)

    def shiftSliceAxis(self, axis):
        return _neutube.ZIntCuboid_shiftSliceAxis(self, axis)

    def shiftSliceAxisInverse(self, axis):
        return _neutube.ZIntCuboid_shiftSliceAxisInverse(self, axis)

    def getDim(self, axis):
        return _neutube.ZIntCuboid_getDim(self, axis)

    def getCenter(self):
        return _neutube.ZIntCuboid_getCenter(self)
    __swig_destroy__ = _neutube.delete_ZIntCuboid

# Register ZIntCuboid in _neutube:
_neutube.ZIntCuboid_swigregister(ZIntCuboid)



